FROM maven:3.5-jdk-7-alpine as builder
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn clean install

FROM frolvlad/alpine-oraclejdk8:slim
COPY --from=builder /usr/src/app/target/spring-boot-docker-0.1.0.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java -jar /app.jar"]